root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '/%locale%'

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
